name: spikeanalysis_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python<3.12
  - numpy
  - scipy
  - matplotlib
  - numba
  - seaborn
  - pandas
  - scikit-learn
  - git
  - black
  - pytest
  - pytest-cov
  - pip
  - pip:
    - git+https://github.com/NeuralEnsemble/python-neo.git
