[tool.pytest.ini_options]
pythonpath = [
  "src/",
]

[project]
name = "spikeanalysis"
author = {name="Zach McKenzie"}
description = "Analysis of Spike Trains"
requires-python = ">=3.9"

dependencies = [
  "numpy",
  "neo>=0.11.1",
  "tqdm",
  "scipy",
  "matplotlib",
  "pandas",
  "numba",
]

[build-system]
requires = ["setuptools>=62.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.exclude-package-data]
spikeanalysis = ["**/test/*]

[tool.setuptools.packages.find]
where = ["src"]
include = ["spikeanalysis*"]
namespaces = false
